spring:
  application:
    name: veganplanet-system
  cloud:
    nacos:
      discovery:
        namespace:
        group: JAVA
        server-addr: nacos.vegetarianlefty.com:8848
      config:
        file-extension: yaml
        namespace:
        group: JAVA
        server-addr: nacos.vegetarianlefty.com:8848
  config:
    import:
      - optional:nacos:veganplanet-system.yml