server:
  port: 10000
spring:
  application:
    name: veganplanet-system
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://mysql.vaganplanet.com:3306/xss?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: ss
    password: ss

  cloud:
    nacos:
      server-addr: nacos.vaganplanet.com:8848
      config:
        group: JAVA
        namespace: ""
      discovery:
        group: JAVA
        namespace: ""